# SPDX-FileCopyrightText: Copyright (c) 2025 The Newton Developers
# SPDX-License-Identifier: Apache-2.0

"""Public inverse-kinematics API for defining objectives and solving IK problems."""

from ._src.sim.ik import (
    IKJacobianType,
    IKLinearSolver,
    IKObjective,
    IKObjectiveApparentGravity,
    IKObjectiveAxisAlignment,
    IKObjectiveFootContact,
    IKObjectiveFootSkate,
    IKObjectiveGravityTorque,
    IKObjectiveJointLimit,
    IKObjectiveJointReference,
    IKObjectivePosition,
    IKObjectivePositionSet,
    IKObjectiveRotation,
    IKObjectiveRotationSet,
    IKObjectiveSelfCollision,
    IKObjectiveSmoothness,
    IKObjectiveTemporal,
    IKObjectiveVelocityLimit,
    IKObjectiveWorldPlane,
    IKObjectiveWorldPlaneCapsule,
    IKOptimizer,
    IKOptimizerLBFGS,
    IKOptimizerLM,
    IKSampler,
    IKSolver,
    IKSolverTrajectory,
)

__all__ = [
    "IKJacobianType",
    "IKLinearSolver",
    "IKObjective",
    "IKObjectiveApparentGravity",
    "IKObjectiveAxisAlignment",
    "IKObjectiveFootContact",
    "IKObjectiveFootSkate",
    "IKObjectiveGravityTorque",
    "IKObjectiveJointLimit",
    "IKObjectiveJointReference",
    "IKObjectivePosition",
    "IKObjectivePositionSet",
    "IKObjectiveRotation",
    "IKObjectiveRotationSet",
    "IKObjectiveSelfCollision",
    "IKObjectiveSmoothness",
    "IKObjectiveTemporal",
    "IKObjectiveVelocityLimit",
    "IKObjectiveWorldPlane",
    "IKObjectiveWorldPlaneCapsule",
    "IKOptimizer",
    "IKOptimizerLBFGS",
    "IKOptimizerLM",
    "IKSampler",
    "IKSolver",
    "IKSolverTrajectory",
]
